# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Modify taskbar settings
        allowPrerelease: true
      settings:
        Alignment: Left # [KeepCurrentValue, Middle]
        HideLabelsMode: Never # [KeepCurrentValue, WhenFull, Always]
        SearchBoxMode: ShowIconAndLabel # [KeepCurrentValue, ShowIconOnly, SearchBox, Hide]
        TaskViewButton: Show # [KeepCurrentValue, Hide]
        WidgetsButton: Show # [KeepCurrentValue, Hide]
        RestartExplorer: True
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Modify Windows Explorer settings
        allowPrerelease: true
      settings:
        FileExtensions: Hide # [KeepCurrentValue, Hide]
        HiddenFiles: Hide # [KeepCurrentValue, Hide]
        ItemCheckBoxes: Hide # [KeepCurrentValue, Hide]
        RestartExplorer: True
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true
